autoservice/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('automobiliai/', views.automobiliai, name='automobiliai'),
    path('automobiliai/<int:automobilis_id>', views.automobilis, name='automobilis'),
    path('uzsakymai/', views.UzsakymasListView.as_view(), name='uzsakymas'),
    path('uzsakymai/<int:pk>', views.UzsakymasDetailView.as_view(), name='uzsakymas-detail'),
    path('search/', views.search, name='search'),
    path('about/' ,views.about,name='about'),
    path('akcijos/' ,views.akcijos,name='akcijos'),
    path('manoautomobiliai/', views.LoanedUzsakymaiByUserListView.as_view(), name='mano-uzsakymai'),
    path('manoautomobiliai/<int:pk>', views.UzsakymasByUserDetailView.as_view(), name='mano-uzsakymas'),
    path('manoautomobiliai/new', views.UzsakymasByUserCreateView.as_view(), name='mano-uzsakymas-new'),
    path('manoautomobiliai/<int:pk>/update', views.UzsakymasByUserUpdateView.as_view(), name='mano-uzsakymas-update'),
    path('manoautomobiliai/<int:pk>/delete', views.UzsakymasByUserDeleteView.as_view(), name='mano-uzsakymas-delete'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
    path('main/', views.profilis2, name='main'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
urlpatterns = [
                  path('autoservice/', include('autoservice.urls')),
                  path('admin/', admin.site.urls),
                  path('', RedirectView.as_view(url='autoservice/', permanent=True)),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('tinymce/', include('tinymce.urls')),
              ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

autoservice/models.py
from datetime import date
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField


class AutomobiloModelis(models.Model):
    marke = models.CharField('Markė', max_length=100, help_text='Iveskite markę (pvz. Ford )')
    modelis = models.CharField('Modelis', max_length=100, help_text='Iveskite modelį (pvz. Focus )')

    def __str__(self):
        return f'{self.marke} {self.modelis}'

    class Meta:
        verbose_name = 'Automobilio Modelis'
        verbose_name_plural = 'Automobilio modeliai'


class Automobilis(models.Model):
    valstybinis_nr = models.CharField('Valstybinis_NR', max_length=15, help_text='Iveskite Valstybini nr.(pvz AAA000)')
    automobilio_modelis_id = models.ForeignKey('AutomobiloModelis', on_delete=models.CASCADE, null=False,
                                               related_name='automobiliomodelis')
    vin_kodas = models.CharField('VIN_Kodas', max_length=17, help_text='Iveskite VIN (pvz.3C6UR5CJXEG146621)')
    klientas = models.CharField('Klientas', max_length=100, help_text='Vardas Pavarde pvz(Juozas Juozaitis)')
    aprasymas = HTMLField('Aprasymas', help_text='Aprasymas', null=True)
    cover = models.ImageField('Viršelis', upload_to='covers', null=True, blank=True)

    def __str__(self):
        return f'Valstybinis NR: {self.valstybinis_nr}   VIN: {self.vin_kodas}   Klientas: {self.klientas}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.cover.path)
        if img.height > 225 or img.width > 400:
            output_size = (400, 225)
            img.thumbnail(output_size)
            img.save(self.cover.path)

    def display_automobilis_modelis(self):
        return f'{self.automobilio_modelis_id.marke} {self.automobilio_modelis_id.modelis}'

    display_automobilis_modelis.short_description = 'Automobilis'

    class Meta:
        verbose_name_plural = "Automobiliai"


class Uzsakymas(models.Model):
    data = models.DateField('Data', null=True, blank=True)
    automobilis_id = models.ForeignKey('Automobilis', on_delete=models.CASCADE, null=False)
    bus_sutvarkyta = models.DateField('Bus sutvarkyta', null=True, blank=True)
    savininkas = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.bus_sutvarkyta and date.today() > self.bus_sutvarkyta:
            return True
        return False

    LOAN_STATUS = (
        ('uzregistruotas', 'Uzregistruota'),
        ('eileje', 'Eileje'),
        ('tvarkomas', 'Tvarkoma'),
        ('galima atsiimti', 'Galima atsiimti'),
        ('atlikta', 'Atlikta'),
    )

    status = models.CharField(
        max_length=20,
        choices=LOAN_STATUS,
        blank=True,
        default='Uzregistruotas',
        help_text='Statusas',
    )

    class Meta:
        ordering = ['bus_sutvarkyta']
        verbose_name_plural = "Uzsakymai"

    def __str__(self):
        return (f'Užsakymo NR.{self.id} {self.data} ,Statusas: {self.status} - '
                f'Automobilis: {self.automobilis_id.valstybinis_nr} VIN:{self.automobilis_id.vin_kodas}')

    def display_automobilis_val_nr(self):
        return self.automobilis_id.valstybinis_nr

    display_automobilis_val_nr.short_description = 'Valstybinis NR.'

    def display_automobilis_vin(self):
        return self.automobilis_id.vin_kodas

    display_automobilis_vin.short_description = 'VIN Kodas.'

    def display_automobilis_client(self):
        return self.automobilis_id.klientas

    display_automobilis_client.short_description = 'Klientas'

    def display_automobilis_marke(self):
        return self.automobilis_id.automobilio_modelis_id

    display_automobilis_marke.short_description = 'Gamintojas/Marke'


#
class UzsakymoEilute(models.Model):
    paslauga_id = models.ForeignKey('Paslauga', on_delete=models.CASCADE, null=False)
    uzsakymo_id = models.ForeignKey('Uzsakymas', on_delete=models.CASCADE, null=False)
    kiekis = models.CharField('Kiekis', max_length=250, help_text='Iveskite kieki')

    #
    def __str__(self):
        return (f'Valstybinis NR: {self.uzsakymo_id.automobilis_id.valstybinis_nr} '
                f'Paslauga: {self.paslauga_id.pavadinimas} Kiekis: {self.kiekis}')

    class Meta:
        verbose_name = 'Uzsakymo eilutes'
        verbose_name_plural = 'Uzsakymo eilute'


class Paslauga(models.Model):
    pavadinimas = models.CharField('Pavadinimas', max_length=100,
                                   help_text='Iveskite paslaugos pavadinima (pvz.Tepalu keitimas)')
    kaina = models.IntegerField('Kaina', help_text='Iveskite kaina paslaugos(pvz: 199)')

    def __str__(self):
        return f'{self.pavadinimas}, Kaina: {self.kaina}'

    class Meta:
        verbose_name = 'Paslauga'
        verbose_name_plural = 'Paslaugos'


class UzsakymasReview(models.Model):
    uzsakymas = models.ForeignKey('Uzsakymas', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)

    class Meta:
        verbose_name = "Atsiliepimas"
        verbose_name_plural = 'Atsiliepimai'
        ordering = ['-date_created']


class Akcijos(models.Model):
    data = models.DateField('Data', null=True, blank=True)
    aprasymas = HTMLField('Aprasymas', help_text='Aprasymas', null=True)


class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default="profile_pics/no-image.jpg", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

autoservice/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template.context_processors import request
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormMixin

from .forms import UzsakymasReviewForm, UserUpdateForm, ProfilisUpdateForm, UserUzsakymasCreateForm
from .models import AutomobiloModelis, Automobilis, Uzsakymas, UzsakymoEilute, Paslauga, Akcijos


def index(request):
    paslaugu_kiekis = Paslauga.objects.all().count()
    atlikti_uzsakymai = Uzsakymas.objects.filter(status__exact='atlikta').count()
    automobiliu_kiekis = Automobilis.objects.all().count()
    uzregistruoti_auto = Uzsakymas.objects.filter(status__exact='uzregistruotas').count()
    tvarkomi_auto = Uzsakymas.objects.filter(status__in=['eileje', 'tvarkomas']).count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    # # perduodame informaciją į šabloną žodyno pavidale:
    context = {
        'paslaugu_kiekis': paslaugu_kiekis,
        'atlikti_uzsakymai': atlikti_uzsakymai,
        'automobiliu_kiekis': automobiliu_kiekis,
        'uzregistruoti_auto': uzregistruoti_auto,
        'tvarkomi_auto': tvarkomi_auto,
        'num_visits': num_visits,
    }

    # renderiname index.html, su duomenimis kintamąjame context
    return render(request, 'index.html', context=context)


def automobiliai(request):
    paginator = Paginator(Automobilis.objects.all().order_by('id'), 2)
    page_number = request.GET.get('page')
    automobiliai = paginator.get_page(page_number)
    context = {
        'automobiliai': automobiliai
    }
    # print(automobiliai)
    return render(request, 'automobiliai.html', context=context)


def automobilis(request, automobilis_id):
    single_automobilis = get_object_or_404(Automobilis, pk=automobilis_id)
    # print(single_automobilis)
    return render(request, 'automobilis.html', {'automobilis': single_automobilis})


class UzsakymasListView(generic.ListView):
    model = Uzsakymas
    paginate_by = 4
    template_name = 'uzsakymas_list.html'
    # queryset = Uzsakymas.objects.filter(status__in=['eileje', 'tvarkomas','uzregistruotas','galima atsiimti'])



class UzsakymasDetailView(FormMixin,generic.DetailView):
    model = Uzsakymas
    template_name = 'uzsakymas_detail.html'
    form_class = UzsakymasReviewForm

    def get_success_url(self):
        return reverse('uzsakymas-detail', kwargs={'pk': self.object.id})

        # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


    def form_valid(self, form):
        form.instance.uzsakymas = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(UzsakymasDetailView, self).form_valid(form)

def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = Automobilis.objects.filter(Q(valstybinis_nr__icontains=query)
                                                | Q(vin_kodas__icontains=query) | Q(klientas__icontains=query)
                                                | Q(automobilio_modelis_id__marke__icontains=query)
                                                | Q(automobilio_modelis_id__modelis__icontains=query))
    return render(request, 'search.html', {'automobiliai': search_results, 'query': query})

def about(request):
    return render(request, 'about.html')


class LoanedUzsakymaiByUserListView(LoginRequiredMixin, generic.ListView):
    model = Uzsakymas
    template_name = 'user_uzsakymai.html'
    paginate_by = 10

    def get_queryset(self):
        return Uzsakymas.objects.filter(savininkas=self.request.user).order_by('bus_sutvarkyta')

    # def get_queryset(self):
    #     return Uzsakymas.objects.filter(savininkas=self.request.user).filter(status__in=['eileje', 'tvarkomas','uzregistruotas','galima atsiimti']).order_by('bus_sutvarkyta')


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'register.html')



def akcijos(request):
    akcijos = Akcijos.objects.all()
    context = {
        'akcijos': akcijos
    }
    return render(request, 'akcijos.html', context=context)

@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profilis.html', context)


@login_required
def profilis2(request):
    return render(request, 'main.html')


class UzsakymasByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Uzsakymas
    template_name = 'user_uzsakymas.html'


class UzsakymasByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Uzsakymas
    # fields = ['automobilis_id', 'bus_sutvarkyta']
    success_url = "/autoservice/manoautomobiliai/"
    template_name = 'user_uzsakymas_form.html'
    form_class = UserUzsakymasCreateForm

    def form_valid(self, form):
        form.instance.savininkas = self.request.user
        return super().form_valid(form)

class UzsakymasByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Uzsakymas
    # fields = ['automobilis_id', 'bus_sutvarkyta']
    success_url = "/autoservice/manoautomobiliai/"
    template_name = 'user_uzsakymas_form.html'
    form_class = UserUzsakymasCreateForm

    def form_valid(self, form):
        form.instance.savininkas = self.request.user
        return super().form_valid(form)

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.savininkas

class UzsakymasByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Uzsakymas
    success_url = "/autoservice/manoautomobiliai/"
    template_name = 'user_uzsakymas_delete.html'

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.savininkas

autoservice/templates/about.html
{% extends "base.html" %}

{% block content %}
  <p><h4>Kontaktai:</h4></p>
<p><strong> Mūsų el.paštas:</strong>   kiesa.autoservice@inbox.lt</p>
<p><strong> Telefono numeris:</strong>   86000001</p>
<h5>Mūsų adresas:</h5>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2296.0482764328744!2d23.889223599999998!3d54.866963399999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46e7231f86cacbc7%3A0xe2a0b2717fb4bad6!2zVE9Exb3EliBrZWJhYmluxJc!5e0!3m2!1slt!2slt!4v1733320432913!5m2!1slt!2slt" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
{% endblock %}

autoservice/templates/akcijos.html
{% extends "base.html" %}
{% block content %}
    {% if akcijos %}
        {% for akcija in akcijos %}
            <div class="akcija container">
                <p class="data"><strong>Data:</strong> {{ akcija.data }}</p>
                <div class="aprasymas">
                    <div>
                        {{ akcija.aprasymas|safe }}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Nėra akcijų.</p>
    {% endif %}
{% endblock %}

autoservice/templates/automobiliai.html
{% extends "base.html" %}
 {% load static %}
{% block content %}
<h1>Automobiliai</h1>
<p>Mūsų automobilių sąrašas.</p>
<div class="row">
      {% for automobilis in automobiliai %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if automobilis.cover %}
              <img src="{{ automobilis.cover.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="{% static 'img/no-image.jpg' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <h7 class="card-subtitle mb-2 text-muted"><strong>Valstybinis NR.</strong> {{ automobilis.valstybinis_nr }}</h7>
              <p class="card-text"><a href="{% url 'automobilis' automobilis.id %}"> Modelis/Marke:
                  {{automobilis.automobilio_modelis_id}}</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
<div class="container puslapiai">
    <nav aria-label="...">
        {% if automobiliai.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in automobiliai.paginator.page_range %}
                    {% if automobiliai.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

autoservice/templates/automobilis.html
{% extends "base.html" %}
 {% load static %}
{% block content %}
<div class="container automobilis">
    <h5>Automobilis: {{ automobilis.automobilio_modelis_id }}</h5>
    {% if automobilis.cover %}
    <img src="{{ automobilis.cover.url }}" style="margin-bottom: 20px;">
    {% else %}
    <img src="{% static 'img/no-image.jpg' %}" style="margin-bottom: 20px;">
    {% endif %}
    <hr/>
    <p>Klientas: {{ automobilis.klientas }}</p>
    <p>Automobilio modelis: {{ automobilis.automobilio_modelis_id }}</p>
    <p>Valstybinis nr: {{ automobilis.valstybinis_nr }}</p>
    <p>VIN: {{ automobilis.vin_kodas }}</p>
    <p>Aprasymas: </strong>{{ automobilis.aprasymas | safe }}</p>
    </hr>
    </br>
</div>
{% endblock %}

autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Kiešos autoservise</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <picture>
    <source srcset="https://i.postimg.cc/5yyTmBht/pngwing-com-1.png"
            media="(min-width: 600px)">
    <img src="URL/file directory" alt=""/>
</picture>
    <a class="navbar-brand">Kiešos autoservise</a>
    <ul class="navbar-nav mx-2">
      {% if user.is_authenticated %}
      <li class="nav-item"><a class="btn" href="{% url 'main' %}">
        <svg class="bi bi-person" width="1.2em" height="1.2em" viewBox="0 0 16 16" fill="currentColor"
             xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
                d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                clip-rule="evenodd"/>
        </svg>
        {{ user.get_username }}</a></li>
      <li class="nav-item"><a class="btn" href="{% url 'mano-uzsakymai' %}">Mano Automobiliai</a></li>
        <li class="nav-item"><a class="btn" href="{% url 'mano-uzsakymas-new'%}?next=/autoservice">Naujas užsakymas</a></li>
      <li class="nav-item">
        <form method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button class="btn" type="submit">Atsijungti</button>
        </form>
      </li>
      {% else %}
      <li class="nav-item"><a class="btn" href="{% url 'login'%}">Prisijungti</a></li>
      <li class="nav-item"><a class="btn" href="{% url 'register'%}">Registruotis</a></li>
      {% endif %}
      <li class="nav-item active"><a class="btn" href="{% url 'index' %}">Pradžia</a></li>
        <li class="nav-item active"><a class="btn" href="{% url 'akcijos' %}">Naujienos</a></li>
      <li class="nav-item active"><a class="btn" href="{% url 'automobiliai' %}">Visi automobiliai</a></li>
      <li class="nav-item active"><a class="btn" href="{% url 'uzsakymas' %}">Uzsakymai</a></li>
      <li class="nav-item active"><a class="btn" href="{% url 'about' %}">Informacija</a></li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
      <input class="form-control me-2" name="query" class="form-control" type="text" placeholder="Paieška">
      <button class="btn" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="col-sm-10 ">
  {% block content %}
  {% endblock %}
</div>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                {{ message }}
        </div>
    {% endfor %}
{% endif %}
</body>
</html>

autoservice/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Kiešos autoservise</h1>
<p>Sveiki atvyke i Kiešos 500 pinigų autoservisą!</p>
<p>Statistika serviso:</p>
<ul>
    <li><strong>Atliekamų paslaugų kiekis:</strong> {{ paslaugu_kiekis }}</li>
    <li><strong>Atlikti darbai:</strong> {{ atlikti_uzsakymai }}</li>
    <li><strong>Automobiliu kiekis:</strong> {{ automobiliu_kiekis }}</li>
    <li><strong>Uzregistruoti automobiliai darbams:</strong> {{ uzregistruoti_auto }}</li>
    <li><strong>Tvarkomi siuo metu automobiliai:</strong> {{ tvarkomi_auto }}</li>
</ul>
<p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
</br>
{% endblock %}

autoservice/templates/uzsakymas_detail.html
{% extends "base.html" %}

{% block content %}
<h5>Valstybinis nr. {{ uzsakymas.automobilis_id.valstybinis_nr }}</h5>
<p><strong>Data: </strong> {{ uzsakymas.data }}</p>
<p><strong>VIN: </strong>{{ uzsakymas.automobilis_id.vin_kodas }}</p>
<p><strong>Modelis/Marke: </strong>{{ uzsakymas.automobilis_id.automobilio_modelis_id }}</p>
<p><strong>Klientas: </strong>{{ uzsakymas.automobilis_id.klientas }}</p>
<p><strong>Statusas: </strong>{{ uzsakymas.status }}</p>
<h4>Paslaugos:</h4>
{% for eilute in uzsakymas.uzsakymoeilute_set.all %}
<div style="margin-left:20px;margin-top:20px">
  <p><strong>Paslauga:</strong> {{ eilute.paslauga_id.pavadinimas }} </p>
  <p><strong>Kaina</strong> {{ eilute.paslauga_id.kaina }} €</p>
  <p><strong>Kiekis:</strong> {{ eilute.kiekis }}</p>
</div>
</br>
  <h4>Atsiliepimai:</h4>
  {% if uzsakymas.uzsakymasreview_set.all %}
    {% for review in uzsakymas.uzsakymasreview_set.all %}
      <hr>

       <img class="rounded-circle" src="{{review.reviewer.profilis.nuotrauka.url}}"width="100" height="75">
      <strong>{{ review.reviewer }}  </strong>, <em>Data: {{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>Užsakymas neturi atsiliepimų</p>
  {% endif %}
{% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Palikite atsiliepimą:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Išsaugoti">
    </form>
  </div>
  {% endif %}
{% endfor %}
{% endblock %}